# Generated by Django 4.0.8 on 2023-01-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('PRAYER_REQUEST', 'PRAYER_REQUEST'), ('COUNSELLING', 'COUNSELLING'), ('OTHERS', 'OTHERS'), ('WHISTLEBLOWING', 'WHISTLEBLOWING'), ('SUGGESTION', 'SUGGESTION'), ('TESTIMONY', 'TESTIMONY')], max_length=20),
        ),
    ]
