# Generated by Django 4.0.8 on 2023-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('children', 'children'), ('teeneger', 'teeneger'), ('adult', 'adult')], default='unknown', max_length=20),
        ),
    ]
