# Generated by Django 4.0.8 on 2023-01-21 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
