# Generated by Django 4.0.8 on 2023-01-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customuser_firstname_alter_customuser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('admin', 'admin')], default='user', max_length=50),
            preserve_default=False,
        ),
    ]
