# Generated by Django 4.0.8 on 2023-01-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_memebers_churchgroup_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
