# Generated by Django 4.0.8 on 2023-01-17 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_remove_attendance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
