# Generated by Django 4.0.8 on 2023-01-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options'),
        ('attendance', '0004_alter_attendance_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='event.event'),
        ),
    ]
