# Generated by Django 4.0.8 on 2023-01-18 12:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_uuidtaggeditem_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=blog.models.generateUUID, editable=False, primary_key=True, serialize=False),
        ),
    ]
