# Generated by Django 4.0.8 on 2023-01-16 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
