# Generated by Django 4.0.8 on 2023-01-23 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_end_at_alter_event_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
