# Generated by Django 4.0.8 on 2023-01-25 19:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopodcast',
            name='url',
            field=cloudinary.models.CloudinaryField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
