# Generated by Django 4.0.8 on 2023-01-25 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_alter_videopodcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopodcast',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
