# Generated by Django 4.0.8 on 2023-01-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giving',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
