# Generated by Django 4.0.8 on 2023-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0002_alter_giving_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='giving',
            name='type',
            field=models.CharField(choices=[('OFFERING', 'OFFERING'), ('DONATION', 'DONATION'), ('TITHE', 'TITHE'), ('BUILDING', 'BUILDING')], default='DONATION', max_length=20),
        ),
    ]
