# Generated by Django 4.0.8 on 2023-01-21 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('icon_image', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('hero_image', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('image1', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('image2', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('image3', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('image4', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('image5', models.ImageField(upload_to='site/%Y/%m/%d/')),
                ('audio1', models.FileField(null=True, upload_to='audio/', verbose_name='')),
                ('audio2', models.FileField(null=True, upload_to='audio/', verbose_name='')),
                ('audio3', models.FileField(null=True, upload_to='audio/', verbose_name='')),
                ('video1', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video2', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video3', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
