# Generated by Django 4.0.8 on 2023-01-25 09:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_alter_siteinfo_audio1_alter_siteinfo_audio2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='audio1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio1'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio3'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos1'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos3'),
        ),
    ]
