# Generated by Django 4.0.8 on 2023-01-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0009_siteinfo_audio1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='lock',
            field=models.CharField(default='X', max_length=1, primary_key=True, serialize=False),
        ),
    ]
