# Generated by Django 4.0.8 on 2023-01-25 20:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_videopodcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopodcast',
            name='url',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
