# Generated by Django 4.0.8 on 2023-01-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poll.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20, verbose_name=poll.models.PollCategory)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('poll_instruction', models.TextField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED')], default='DRAFT', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PollCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MULTIPLE_ANSWER', 'MULTIPLE_ANSWER'), ('SINGLE_ANSWER', 'SINGLE_ANSWER'), ('STAR_RATING', 'STAR_RATING'), ('SHORT_ANSWER', 'SHORT_ANSWER')], max_length=20)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.poll')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PollQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, null=True)),
                ('max_field_rating', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='poll.pollquestion')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_response', to='poll.poll')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.pollquestion')),
                ('selected_options', models.ManyToManyField(to='poll.pollquestionoption')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionId', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MULTIPLE_ANSWER', 'MULTIPLE_ANSWER'), ('SINGLE_ANSWER', 'SINGLE_ANSWER'), ('STAR_RATING', 'STAR_RATING'), ('SHORT_ANSWER', 'SHORT_ANSWER')], max_length=20)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='poll.poll')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
