QUESTION_TYPES = (("PRAYER_REQUEST", "PRAYER_REQUEST"), ("COUNSELLING", "COUNSELLING"),
                  ("OTHERS", "OTHERS"), ("WHISTLEBLOWING", "WHISTLEBLOWING"), ("SUGGESTION", "SUGGESTION"), ("TESTIMONY", "TESTIMONY"))
