POLL_STATUS = (("ACTIVE", "ACTIVE"), ("DEACTIVATED", "DEACTIVATED"))

QUESTION_TYPES = (
    ('MULTIPLE_ANSWER', 'MULTIPLE_ANSWER'),
    ('SINGLE_ANSWER', 'SINGLE_ANSWER'),
    ('STAR_RATING', 'STAR_RATING'),
    ('SHORT_ANSWER', 'SHORT_ANSWER'),
)
