# Generated by Django 4.0.8 on 2023-01-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.ForeignKey(default='GENRIC', max_length=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='poll.pollcategory'),
        ),
    ]
