# Generated by Django 4.0.8 on 2023-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_pollcategory_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollAnswer',
        ),
    ]
