# Generated by Django 4.0.8 on 2023-01-16 22:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
