# Generated by Django 4.0.8 on 2023-01-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='title',
        ),
    ]
