# Generated by Django 4.0.8 on 2023-01-25 09:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_alter_siteinfo_audio1_alter_siteinfo_audio2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='audio1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='audio1'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='audio2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='audio3'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='icon_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='icon_image'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image5'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='videos1'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='videos3'),
        ),
    ]
