# Generated by Django 4.0.8 on 2023-01-25 09:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_alter_siteinfo_image1_alter_siteinfo_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='audio1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='audio3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='icon_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
