# Generated by Django 4.0.8 on 2023-01-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_alter_siteinfo_audio1_alter_siteinfo_audio2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='audio1',
        ),
    ]
